# Generated by Django 4.1.2 on 2022-10-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=50, verbose_name="Категория"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=20, unique=True, verbose_name="URL"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestBurner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.allitems",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Burner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "photo_main",
                    models.ImageField(upload_to="photos/", verbose_name="Фото 1"),
                ),
                (
                    "photo_second",
                    models.ImageField(
                        blank=True, upload_to="photos/", verbose_name="Фото 2"
                    ),
                ),
                (
                    "photo_third",
                    models.ImageField(
                        blank=True, upload_to="photos/", verbose_name="Фото 3"
                    ),
                ),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                ("power", models.FloatField(verbose_name="Мощность")),
                ("material", models.CharField(max_length=50, verbose_name="Материал")),
                (
                    "pressure_min",
                    models.FloatField(verbose_name="Минимальное давление"),
                ),
                (
                    "pressure_max",
                    models.FloatField(verbose_name="Максимальное давление"),
                ),
                ("autofire", models.BooleanField(verbose_name="Автоподжиг")),
                ("weight", models.FloatField(verbose_name="Вес")),
                ("size_x", models.IntegerField(verbose_name="Длина")),
                ("size_y", models.IntegerField(verbose_name="Ширина")),
                ("size_z", models.IntegerField(verbose_name="Высота")),
                (
                    "flame_control",
                    models.BooleanField(verbose_name="Регулирование пламени"),
                ),
                (
                    "fuel_type",
                    models.CharField(max_length=50, verbose_name="Тип топлива"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="allitems",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.category"
            ),
        ),
    ]
