# Generated by Django 4.1.2 on 2022-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("photo", models.ImageField(upload_to="photos/")),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                ("power", models.FloatField()),
                ("material", models.CharField(max_length=50)),
                ("pressure_min", models.FloatField()),
                ("pressure_max", models.FloatField()),
                ("autofire", models.BooleanField()),
                ("weight", models.FloatField()),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
                ("size_z", models.IntegerField()),
                ("flame_control", models.BooleanField()),
                ("fuel_type", models.CharField(max_length=50)),
            ],
        ),
    ]
