# Generated by Django 4.1.2 on 2022-10-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="autofire",
            field=models.BooleanField(verbose_name="Автоподжиг"),
        ),
        migrations.AlterField(
            model_name="item",
            name="flame_control",
            field=models.BooleanField(verbose_name="Регулирование пламени"),
        ),
        migrations.AlterField(
            model_name="item",
            name="fuel_type",
            field=models.CharField(max_length=50, verbose_name="Тип топлива"),
        ),
        migrations.AlterField(
            model_name="item",
            name="material",
            field=models.CharField(max_length=50, verbose_name="Материал"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=models.ImageField(upload_to="photos/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="item",
            name="power",
            field=models.FloatField(verbose_name="Мощность"),
        ),
        migrations.AlterField(
            model_name="item",
            name="pressure_max",
            field=models.FloatField(verbose_name="Максимальное давление"),
        ),
        migrations.AlterField(
            model_name="item",
            name="pressure_min",
            field=models.FloatField(verbose_name="Минимальное давление"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="item",
            name="size_x",
            field=models.IntegerField(verbose_name="Длина"),
        ),
        migrations.AlterField(
            model_name="item",
            name="size_y",
            field=models.IntegerField(verbose_name="Ширина"),
        ),
        migrations.AlterField(
            model_name="item",
            name="size_z",
            field=models.IntegerField(verbose_name="Высота"),
        ),
        migrations.AlterField(
            model_name="item",
            name="weight",
            field=models.FloatField(verbose_name="Вес"),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
