# Generated by Django 4.1.2 on 2022-10-20 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_alter_item_autofire_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Burner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("photo", models.ImageField(upload_to="photos/", verbose_name="Фото")),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                ("power", models.FloatField(verbose_name="Мощность")),
                ("material", models.CharField(max_length=50, verbose_name="Материал")),
                (
                    "pressure_min",
                    models.FloatField(verbose_name="Минимальное давление"),
                ),
                (
                    "pressure_max",
                    models.FloatField(verbose_name="Максимальное давление"),
                ),
                ("autofire", models.BooleanField(verbose_name="Автоподжиг")),
                ("weight", models.FloatField(verbose_name="Вес")),
                ("size_x", models.IntegerField(verbose_name="Длина")),
                ("size_y", models.IntegerField(verbose_name="Ширина")),
                ("size_z", models.IntegerField(verbose_name="Высота")),
                (
                    "flame_control",
                    models.BooleanField(verbose_name="Регулирование пламени"),
                ),
                (
                    "fuel_type",
                    models.CharField(max_length=50, verbose_name="Тип топлива"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=50, verbose_name="Категория"),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="burner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
                verbose_name="Категория",
            ),
        ),
    ]
