# Generated by Django 4.1.2 on 2022-10-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_testgorelka_item_remove_burner_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="burner",
            name="photo_main",
        ),
        migrations.RemoveField(
            model_name="burner",
            name="photo_second",
        ),
        migrations.RemoveField(
            model_name="burner",
            name="photo_third",
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="photos/<django.db.models.fields.related.ForeignKey>/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.allitems",
                        verbose_name="Предмет",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Heater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                ("fuel", models.CharField(max_length=20, verbose_name="Тип топлива")),
                (
                    "fuel_consumption",
                    models.IntegerField(verbose_name="Расход топлива"),
                ),
                ("boiling_time", models.FloatField(verbose_name="Время закипания")),
                ("size_x", models.IntegerField(verbose_name="Длина")),
                ("size_y", models.IntegerField(verbose_name="Ширина")),
                ("size_z", models.IntegerField(verbose_name="Высота")),
                ("weight", models.FloatField(verbose_name="Вес")),
                ("piezo_ignition", models.BooleanField(verbose_name="Пьезоподжиг")),
                ("material", models.CharField(max_length=50, verbose_name="Материал")),
                ("power", models.FloatField(verbose_name="Мощность")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.allitems",
                        verbose_name="Предмет",
                    ),
                ),
            ],
        ),
    ]
