# Generated by Django 4.1.2 on 2022-10-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_burner_alter_category_category_name_delete_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="burner",
            name="photo",
        ),
        migrations.AddField(
            model_name="burner",
            name="photo_main",
            field=models.ImageField(
                default=0,
                upload_to="photos/<django.db.models.fields.CharField>/",
                verbose_name="Фото 1",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="burner",
            name="photo_second",
            field=models.ImageField(
                blank=True,
                upload_to="photos/<django.db.models.fields.CharField>/",
                verbose_name="Фото 2",
            ),
        ),
        migrations.AddField(
            model_name="burner",
            name="photo_third",
            field=models.ImageField(
                blank=True,
                upload_to="photos/<django.db.models.fields.CharField>/",
                verbose_name="Фото 3",
            ),
        ),
    ]
