# Generated by Django 4.1.2 on 2022-10-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_heater_pressure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burner",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.allitems",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="heater",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.allitems",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="heater",
            name="pressure",
            field=models.FloatField(verbose_name="Давление"),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="photos/", verbose_name="Фото"),
        ),
    ]
