# Generated by Django 4.1.2 on 2022-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_category_slug_alter_burner_photo_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=20, verbose_name="URL"),
        ),
    ]
