# Generated by Django 4.1.2 on 2022-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_heater_boiling_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allitems",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
