# Generated by Django 4.1.2 on 2023-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_allitems_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="allitems",
            name="name_lower",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
